---
- name: Appliance Initial
  hosts: all
  vars_files:
    - ../conf/appliance.secrets.conf.yml
    - ../conf/appliance.common.conf.yml
  tasks:
    - name: Install standard packages
      apt:
        name: ['htop', 'tree', 'jq', 'fail2ban', 'vim', 'mosh', 'ufw', 'prometheus-node-exporter', 'python-pip', 'inetutils-traceroute']
        update_cache: yes

    - name: Download jsonnet
      file: state=link src={{appliance_setup_path}}/bin/jsonnet-v0.11.2 dest=/usr/bin/jsonnet mode=a+x force=yes

    - name: Get useful .vimrc for admin user
      get_url: url=https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim dest=/home/{{ appliance_admin_user }}/.vimrc

    - name: Reset UFW firewall
      ufw:
        state=reset

    - name: Allow SSH access on instance
      ufw: >
        rule=allow
        name=OpenSSH

    - name: Set to deny incoming requests by default
      ufw: >
        default=deny

    - name: Turn on UFW
      ufw: >
        state=enabled

    - name: Set memory limit in GRUB
      lineinfile: >
        dest=/etc/default/grub
        regexp=^GRUB_CMDLINE_LINUX_DEFAULT
        line='GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"'

    - name: Load new GRUB config
      command: update-grub

